In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2], axis=1, keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [16]:
dframe1

X         Y         Z
0  0.814677 -0.008362 -1.129127
1 -2.079628  1.187809 -0.993201
2  0.317196 -0.407626 -1.026031
3 -0.363257 -0.953413  0.830226

In [19]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [20]:
dframe2

Y         Q         X
0 -0.387158 -0.398052 -0.838520
1 -0.032675  0.666638  0.726668
2 -1.138229 -1.851954 -0.295270

In [21]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.814677 -0.008362 -1.129127
1       NaN -2.079628  1.187809 -0.993201
2       NaN  0.317196 -0.407626 -1.026031
3       NaN -0.363257 -0.953413  0.830226
0 -0.398052 -0.838520 -0.387158       NaN
1  0.666638  0.726668 -0.032675       NaN
2 -1.851954 -0.295270 -1.138229       NaN

In [22]:
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.814677 -0.008362 -1.129127
1       NaN -2.079628  1.187809 -0.993201
2       NaN  0.317196 -0.407626 -1.026031
3       NaN -0.363257 -0.953413  0.830226
4 -0.398052 -0.838520 -0.387158       NaN
5  0.666638  0.726668 -0.032675       NaN
6 -1.851954 -0.295270 -1.138229       NaN