In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-0.50054666,  1.88783117, -0.9707132 , -0.0058851 , -1.40948487,
       -0.29902279,  0.71049957, -1.02648647,  0.04029193, -0.80808634])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([ 0.20930535,  0.27013015, -0.61825628,  0.55528054,  0.77512709,
        0.29954767, -0.54750191,  0.04677229, -0.99400605,  1.26693342])

In [11]:
np.add(A,B)

array([ -2.91241308e-01,   2.15796132e+00,  -1.58896948e+00,
         5.49395440e-01,  -6.34357780e-01,   5.24881523e-04,
         1.62997657e-01,  -9.79714178e-01,  -9.53714123e-01,
         4.58847079e-01])

In [12]:
np.maximum(A,B)

array([ 0.20930535,  1.88783117, -0.61825628,  0.55528054,  0.77512709,
        0.29954767,  0.71049957,  0.04677229,  0.04029193,  1.26693342])